// Lista EIXO de remédios e vacinas (marca + laboratório).
// Regra: carência vem da BULA do produto, nunca do princípio ativo — a mesma molécula
// muda de carência conforme concentração e formulação (ex.: ivermectina 1% x 3,15%).
// Só entra item com fonte e data de conferência. Carência desconhecida fica null
// e o produto não libera venda até o usuário preencher.
//
// Campos:
//   key            identificador fixo (não mudar depois de publicado)
//   brand          nome comercial
//   laboratory     laboratório fabricante
//   activeIngredient, category (mesmas categorias da Farmácia)
//   presentation   texto livre curto
//   route          via de aplicação
//   dose           texto da bula
//   slaughterWithdrawalDays / milkWithdrawalDays  (null = não informado na bula / não usar)
//   refrigerated
//   tags           marcações usadas pelas regras da Sanidade (ex.: BRUCELOSE_B19)
//   notes          cuidados de uso
//   source         de onde saiu a carência
//   reviewedAt     data da conferência (AAAA-MM-DD)

export const PHARMACY_CATALOG_REVISION = '2026-09-16.3';

const BULA = 'bula publicada (bulario.vet.br)';

export const PHARMACY_CATALOG = [
    // ── Vacinas obrigatórias ──
    {
        key: 'abor-vac-zoetis', brand: 'Abor-Vac', laboratory: 'Zoetis',
        activeIngredient: 'Brucella abortus amostra B19 (viva)', category: 'VACINA', tags: ['BRUCELOSE_B19'],
        presentation: 'Liofilizada + diluente', route: 'Subcutânea, atrás da paleta', dose: '2 mL, dose única',
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: 'Só fêmeas de 3 a 8 meses. Nunca em machos. Usar até 2 h após reconstituir. Aplicação por veterinário cadastrado. Evitar contato com olhos, boca e pele. Carência não consta na bula.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'bovilis-rb51-msd', brand: 'Bovilis RB-51', laboratory: 'MSD Saúde Animal',
        activeIngredient: 'Brucella abortus amostra RB51 (viva)', category: 'VACINA', tags: ['BRUCELOSE_RB51'],
        presentation: 'Liofilizada + diluente', route: 'Subcutânea', dose: '2 mL',
        slaughterWithdrawalDays: 21, milkWithdrawalDays: null, refrigerated: true,
        notes: 'Fêmeas acima de 8 meses não vacinadas com B19 na idade certa. Nunca em machos. Usar até 60 min após reconstituir. Aplicador com luvas e óculos.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'raivacel-multi-msd', brand: 'Raivacel Multi', laboratory: 'MSD Saúde Animal (antiga Vallée)',
        activeIngredient: 'Vírus da raiva inativado', category: 'VACINA', tags: ['RAIVA'],
        presentation: 'Frasco multidose', route: 'Intramuscular ou subcutânea', dose: '2 mL',
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: 'Primovacinados: reforço 30 dias após a 1ª dose. Revacinação anual. Não congelar. Carência não consta na bula.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    // ── Vacinas estratégicas ──
    {
        key: 'sintoxan-polivalente-t-boehringer', brand: 'Sintoxan Polivalente T', laboratory: 'Boehringer Ingelheim (antiga Merial)',
        activeIngredient: 'Clostridioses + tétano (inativada)', category: 'VACINA', tags: ['CLOSTRIDIOSE'],
        presentation: 'Frasco multidose', route: 'Subcutânea, tábua do pescoço', dose: '3 mL',
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: 'Primovacinação: 2 doses com 4 a 6 semanas de intervalo. Revacinação anual. Agitar antes de usar. Não vacinar animais doentes ou estressados. Carência não consta na bula.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'bovilis-poli-star-t-msd', brand: 'Bovilis Poli-Star T', laboratory: 'MSD Saúde Animal',
        activeIngredient: 'Clostridioses + tétano + botulismo (inativada)', category: 'VACINA', tags: ['CLOSTRIDIOSE', 'BOTULISMO'],
        presentation: 'Frasco multidose', route: 'Subcutânea', dose: '5 mL (bovinos)',
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: 'Nunca vacinados: 2 doses com 4 semanas de intervalo. Revacinação anual. Não congelar. Carência não consta na bula.',
        source: 'site do fabricante', reviewedAt: '2026-09-16',
    },
    {
        key: 'vision-10-msd', brand: 'Vision 10', laboratory: 'MSD Saúde Animal',
        activeIngredient: 'Clostridioses + tétano (inativada)', category: 'VACINA', tags: ['CLOSTRIDIOSE'],
        presentation: 'Frasco multidose', route: 'Subcutânea', dose: '2 mL (bovinos)',
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: true,
        notes: 'Primovacinação: 2 doses com 6 semanas de intervalo. Revacinação anual. Frasco aberto: usar em até 8 h.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'cattlemaster-4-l5-zoetis', brand: 'CattleMaster 4+L5', laboratory: 'Zoetis',
        activeIngredient: 'IBR, BVD, PI3, BRSV + leptospirose', category: 'VACINA', tags: ['REPRODUTIVA', 'IBR_BVD', 'LEPTOSPIROSE'],
        presentation: 'Liofilizada + diluente', route: 'Intramuscular', dose: '5 mL',
        slaughterWithdrawalDays: 21, milkWithdrawalDays: null, refrigerated: true,
        notes: 'Primovacinação: 2 doses com 2 a 4 semanas de intervalo. Revacinação anual. Usar todo o conteúdo após abrir. Ter adrenalina à mão (risco de reação alérgica).',
        source: 'bula do fabricante', reviewedAt: '2026-09-16',
    },
    {
        key: 'leptoferm-5-zoetis', brand: 'Leptoferm 5/2 mL', laboratory: 'Zoetis',
        activeIngredient: 'Leptospirose (inativada)', category: 'VACINA', tags: ['LEPTOSPIROSE'],
        presentation: 'Frasco multidose', route: 'Intramuscular', dose: '2 mL',
        slaughterWithdrawalDays: 21, milkWithdrawalDays: null, refrigerated: true,
        notes: 'Bovinos: dose única e revacinação anual. Não congelar.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    // ── Endectocidas (vermes, carrapato, berne) ──
    {
        key: 'ivomec-gold-boehringer', brand: 'Ivomec Gold', laboratory: 'Boehringer Ingelheim',
        activeIngredient: 'Ivermectina 3,15%', category: 'ANTIPARASITARIO',
        presentation: 'Solução injetável', route: 'Subcutânea, na frente ou atrás da paleta', dose: '1 mL / 50 kg',
        slaughterWithdrawalDays: 122, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Longa ação. Não usar em vacas em lactação nem até 122 dias antes do parto (leite para consumo). Agitar antes de usar.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'ivomec-pour-on-boehringer', brand: 'Ivomec Pour-On', laboratory: 'Boehringer Ingelheim',
        activeIngredient: 'Ivermectina 0,5%', category: 'ANTIPARASITARIO',
        presentation: 'Solução pour-on', route: 'Dorso, da cernelha à garupa', dose: '1 mL / 10 kg',
        slaughterWithdrawalDays: 48, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não usar em vacas em lactação nem até 48 dias antes do parto.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'master-lp-ourofino', brand: 'Master LP', laboratory: 'Ourofino',
        activeIngredient: 'Ivermectina 4%', category: 'ANTIPARASITARIO',
        presentation: 'Solução injetável', route: 'Subcutânea', dose: '1 mL / 50 kg',
        slaughterWithdrawalDays: 133, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Longa ação. Não usar em fêmeas produtoras de leite para consumo. Nunca na veia ou no músculo.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'dectomax-zoetis', brand: 'Dectomax', laboratory: 'Zoetis',
        activeIngredient: 'Doramectina 1%', category: 'ANTIPARASITARIO',
        presentation: 'Solução injetável', route: 'Subcutânea ou intramuscular', dose: '1 mL / 50 kg',
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não usar em fêmeas produtoras de leite para consumo. Proteger da luz.',
        source: 'bula do fabricante', reviewedAt: '2026-09-16',
    },
    {
        key: 'cydectin-zoetis', brand: 'Cydectin', laboratory: 'Zoetis',
        activeIngredient: 'Moxidectina 1%', category: 'ANTIPARASITARIO',
        presentation: 'Solução injetável', route: 'Subcutânea, na frente ou atrás da paleta', dose: '1 mL / 50 kg',
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não usar em fêmeas produtoras de leite para consumo.',
        source: 'bula do fabricante', reviewedAt: '2026-09-16',
    },
    // ── Vermífugos ──
    {
        key: 'ripercol-l-150f-zoetis', brand: 'Ripercol L 150F', laboratory: 'Zoetis',
        activeIngredient: 'Fosfato de levamisol 18,8%', category: 'VERMIFUGO',
        presentation: 'Solução injetável', route: 'Subcutânea', dose: '1 mL / 40 kg',
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 2, refrigerated: false,
        notes: null,
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'valbazen-10-cobalto-zoetis', brand: 'Valbazen 10 Cobalto', laboratory: 'Zoetis',
        activeIngredient: 'Albendazol 10% + sulfato de cobalto', category: 'VERMIFUGO',
        presentation: 'Suspensão oral', route: 'Oral, com pistola dosificadora', dose: '2 mL / 20 kg',
        slaughterWithdrawalDays: 14, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não dar a fêmeas nos primeiros 45 dias de prenhez. Não usar em fêmeas produtoras de leite para consumo.',
        source: 'bula do fabricante', reviewedAt: '2026-09-16',
    },
    // ── Carrapaticidas e mosquicidas ──
    {
        key: 'colosso-pulverizacao-ourofino', brand: 'Colosso Pulverização', laboratory: 'Ourofino',
        activeIngredient: 'Cipermetrina 15% + clorpirifós 25% + citronelal 1%', category: 'ANTIPARASITARIO', tags: ['CARRAPATICIDA'],
        presentation: 'Concentrado para diluir', route: 'Pulverização ou banho de imersão', dose: 'Pulverização: 1 L para 800 L de água',
        slaughterWithdrawalDays: 10, milkWithdrawalDays: 3, refrigerated: false,
        notes: 'Não descartar sobras em rios, açudes ou nascentes.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'colosso-pour-on-ourofino', brand: 'Colosso Pour On', laboratory: 'Ourofino',
        activeIngredient: 'Cipermetrina 5% + clorpirifós 7% + citronelal 0,5%', category: 'ANTIPARASITARIO', tags: ['CARRAPATICIDA'],
        presentation: 'Solução pour-on', route: 'Dorso, da cauda até o meio do pescoço', dose: '10 mL / 100 kg (máx. 50 mL)',
        slaughterWithdrawalDays: 10, milkWithdrawalDays: 3, refrigerated: false,
        notes: null,
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'butox-p-ce25-msd', brand: 'Butox P CE25', laboratory: 'MSD Saúde Animal',
        activeIngredient: 'Deltametrina 2,5%', category: 'ANTIPARASITARIO', tags: ['CARRAPATICIDA'],
        presentation: 'Concentrado para diluir', route: 'Pulverização ou aspersão', dose: '10 mL para 10 L de água (mín. 5 L por animal adulto)',
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não aplicar no calor forte nem em dia de chuva. Não descartar sobras em rios ou açudes. Carência não consta na bula: confirme com o veterinário.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'acatak-pour-on-elanco', brand: 'Acatak Pour-On', laboratory: 'Elanco (antiga Novartis)',
        activeIngredient: 'Fluazuron 2,5%', category: 'ANTIPARASITARIO', tags: ['CARRAPATICIDA'],
        presentation: 'Solução pour-on', route: 'Duas faixas no dorso', dose: '5 mL / 50 kg',
        slaughterWithdrawalDays: 42, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não usar em vacas leiteiras em idade de reprodução. Bezerros mamando em vacas tratadas também cumprem a carência.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    // ── Antibióticos ──
    {
        key: 'terramicina-la-zoetis', brand: 'Terramicina LA', laboratory: 'Zoetis',
        activeIngredient: 'Oxitetraciclina 20%', category: 'ANTIBIOTICO',
        presentation: 'Solução injetável', route: 'Intramuscular profunda ou subcutânea', dose: '1 mL / 10 kg (máx. 10 mL por local)',
        slaughterWithdrawalDays: 28, milkWithdrawalDays: 4, refrigerated: false,
        notes: 'Leite: 96 horas. Casos graves: 2ª dose 3 a 5 dias depois.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'draxxin-zoetis', brand: 'Draxxin', laboratory: 'Zoetis',
        activeIngredient: 'Tulatromicina 10%', category: 'ANTIBIOTICO',
        presentation: 'Solução injetável', route: 'Subcutânea', dose: '1 mL / 40 kg',
        slaughterWithdrawalDays: 18, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não usar em fêmeas produtoras de leite para consumo.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'draxxin-kp-zoetis', brand: 'Draxxin KP', laboratory: 'Zoetis',
        activeIngredient: 'Tulatromicina 10% + cetoprofeno 12%', category: 'ANTIBIOTICO',
        presentation: 'Solução injetável', route: 'Subcutânea', dose: '1 mL / 40 kg',
        slaughterWithdrawalDays: 25, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não usar em fêmeas produtoras de leite para consumo nem em fêmeas com 20 meses ou mais. Não usar junto com outro anti-inflamatório. Frasco aberto: 56 dias.',
        source: 'bula do fabricante', reviewedAt: '2026-09-16',
    },
    {
        key: 'nuflor-injetavel-msd', brand: 'Nuflor Solução Injetável', laboratory: 'MSD Saúde Animal',
        activeIngredient: 'Florfenicol', category: 'ANTIBIOTICO',
        presentation: 'Solução injetável', route: 'Subcutânea (dose única) ou intramuscular no pescoço (2 doses)', dose: 'Dose única: 2 mL / 15 kg; ou 2 doses de 1 mL / 15 kg',
        slaughterWithdrawalDays: 38, milkWithdrawalDays: null, refrigerated: false,
        notes: 'Não usar em fêmeas produtoras de leite para consumo.',
        source: 'site do fabricante', reviewedAt: '2026-09-16',
    },
    {
        key: 'pencivet-plus-ppu-msd', brand: 'Pencivet Plus PPU', laboratory: 'MSD Saúde Animal',
        activeIngredient: 'Penicilinas + estreptomicina + piroxicam', category: 'ANTIBIOTICO',
        presentation: 'Pó + diluente', route: 'Intramuscular profunda', dose: 'Dose única; conferir tabela por peso na bula',
        slaughterWithdrawalDays: 30, milkWithdrawalDays: 5, refrigerated: false,
        notes: 'Leite: 96 a 120 horas. Conservar entre 8 e 25 °C.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'agrovet-plus-elanco', brand: 'Agrovet Plus', laboratory: 'Elanco (antiga Novartis)',
        activeIngredient: 'Benzilpenicilina procaína + di-hidroestreptomicina + piroxicam', category: 'ANTIBIOTICO',
        presentation: 'Suspensão injetável', route: 'Intramuscular profunda, 1 vez ao dia por 3 a 5 dias', dose: '1 mL / 20 kg',
        slaughterWithdrawalDays: 30, milkWithdrawalDays: 3, refrigerated: false,
        notes: 'Leite: 72 horas. Conservar entre 4 e 25 °C.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    // ── Anti-inflamatórios ──
    {
        key: 'banamine-injetavel-msd', brand: 'Banamine Injetável', laboratory: 'MSD Saúde Animal',
        activeIngredient: 'Flunixina meglumina 5%', category: 'ANTI_INFLAMATORIO',
        presentation: 'Solução injetável', route: 'Intramuscular ou intravenosa', dose: '2 mL / 45 kg por dia',
        slaughterWithdrawalDays: 4, milkWithdrawalDays: 2, refrigerated: false,
        notes: 'Leite: 36 horas.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: 'maxicam-2-ourofino', brand: 'Maxicam 2%', laboratory: 'Ourofino',
        activeIngredient: 'Meloxicam 2%', category: 'ANTI_INFLAMATORIO',
        presentation: 'Solução injetável', route: 'Intramuscular ou intravenosa', dose: '2,5 mL / 100 kg',
        slaughterWithdrawalDays: 8, milkWithdrawalDays: 3, refrigerated: false,
        notes: 'Leite: 72 horas.',
        source: BULA, reviewedAt: '2026-09-16',
    },
    // ── Ampliação set/2026 (bulas publicadas, conferidas em 16/09/2026) ──
    {
        key: "clostrisan-8-virbac", brand: "Clostrisan 8", laboratory: "Virbac",
        activeIngredient: "Clostridioses (8 antígenos)", category: "VACINA", tags: ["CLOSTRIDIOSE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Frasco aberto: usar em até 12 horas. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "carbun-vet-polivalente-biovet", brand: "Carbun-Vet Polivalente", laboratory: "Vaxxinova (antiga Biovet)",
        activeIngredient: "Clostridioses (inativada)", category: "VACINA", tags: ["CLOSTRIDIOSE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "3 mL",
        slaughterWithdrawalDays: 21, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não vacinar animais doentes, fracos ou estressados.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "clostrimune-8-labovet", brand: "Clostrimune-8", laboratory: "Labovet",
        activeIngredient: "Clostridioses + tétano", category: "VACINA", tags: ["CLOSTRIDIOSE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não vacinar animais doentes, parasitados ou subnutridos. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "excell-10-venco", brand: "Excell 10", laboratory: "Venco Saúde Animal",
        activeIngredient: "Clostridioses (inativada)", category: "VACINA", tags: ["CLOSTRIDIOSE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não vacinar animais doentes ou debilitados. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "poli-star-msd", brand: "Poli-Star", laboratory: "MSD Saúde Animal (antiga Vallée)",
        activeIngredient: "Clostridioses (inativada)", category: "VACINA", tags: ["CLOSTRIDIOSE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não vacinar animais doentes ou debilitados. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "antirrabica-labovet", brand: "Vacina Antirrábica Inativada", laboratory: "Labovet",
        activeIngredient: "Vírus da raiva inativado", category: "VACINA", tags: ["RAIVA"],
        presentation: "Frasco multidose", route: "Subcutânea ou intramuscular", dose: "2 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não vacinar animais doentes. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "rai-vet-liquida-biovet", brand: "Rai-Vet Líquida", laboratory: "Vaxxinova (antiga Biovet)",
        activeIngredient: "Vírus da raiva inativado", category: "VACINA", tags: ["RAIVA"],
        presentation: "Frasco multidose", route: "Intramuscular ou subcutânea", dose: "2 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Imunidade a partir de 21 dias. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ourovac-raiva-ourofino", brand: "Ourovac Raiva", laboratory: "Ourofino",
        activeIngredient: "Vírus da raiva inativado (cepa PV)", category: "VACINA", tags: ["RAIVA"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "2 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Pode haver reação alérgica. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "bioraiva-biogenesis", brand: "Bioraiva", laboratory: "Biogénesis Bagó",
        activeIngredient: "Vírus da raiva inativado", category: "VACINA", tags: ["RAIVA"],
        presentation: "Frasco multidose", route: "Intramuscular ou subcutânea", dose: "2 mL",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: true,
        notes: "Se a vacina ficar amarela, não use.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "bgs-cell-ceva", brand: "BGS-Cell", laboratory: "Ceva (antiga Hertape)",
        activeIngredient: "Vírus da raiva inativado", category: "VACINA", tags: ["RAIVA"],
        presentation: "Frasco multidose", route: "Subcutânea ou intramuscular", dose: "2 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não deixar fora do gelo nem no sol. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "vacina-ibr-bvd-ceva", brand: "Vacina IBR/BVD", laboratory: "Ceva (antiga Hertape)",
        activeIngredient: "IBR e BVD (inativada)", category: "VACINA", tags: ["REPRODUTIVA", "IBR_BVD"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL, 2 doses com 28 dias de intervalo",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não usar em animais parasitados, subnutridos ou estressados. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "lepto-vacin-biovet", brand: "Lepto-Vacin", laboratory: "Vaxxinova (antiga Biovet)",
        activeIngredient: "Leptospirose (7 sorovares)", category: "VACINA", tags: ["LEPTOSPIROSE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "3 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Usar apenas em animais sadios. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "cattlemaster-gold-fp5-l5-zoetis", brand: "CattleMaster Gold FP 5/L5", laboratory: "Zoetis",
        activeIngredient: "IBR, BVD, PI3, BRSV + leptospirose", category: "VACINA", tags: ["REPRODUTIVA", "IBR_BVD", "LEPTOSPIROSE"],
        presentation: "Liofilizada + diluente", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: 21, milkWithdrawalDays: null, refrigerated: true,
        notes: "Não vacinar nos 21 dias antes do abate.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ivermectan-ucb", brand: "Ivermectan 1%", laboratory: "UCB (Uzinas Chimicas Brasileiras)",
        activeIngredient: "Ivermectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "vertimax-1-swissbras", brand: "Vertimax 1% Injetável", laboratory: "Swissbras",
        activeIngredient: "Ivermectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em vacas em lactação. Nunca na veia ou no músculo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ivomec-injetavel-boehringer", brand: "Ivomec Injetável", laboratory: "Boehringer Ingelheim (antiga Merial)",
        activeIngredient: "Ivermectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em vacas em lactação nem até 35 dias antes do parto.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ivermectina-1-chemitec", brand: "Ivermectina 1% Chemitec", laboratory: "Chemitec",
        activeIngredient: "Ivermectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em vacas leiteiras. Só por via subcutânea.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ivermectina-1-ja", brand: "Ivermectina 1% J.A.", laboratory: "J.A. Saúde Animal",
        activeIngredient: "Ivermectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: false,
        notes: "Nunca na veia. Carência não consta na bula: confirme com o veterinário.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ivermectina-1-bravet", brand: "Ivermectina 1% Bravet", laboratory: "Bravet",
        activeIngredient: "Ivermectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas leiteiras em idade de reprodução.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "iver-vet-3-5-biovet", brand: "Iver-Vet 3,5%", laboratory: "Vaxxinova (antiga Biovet)",
        activeIngredient: "Ivermectina 3,5%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 109, milkWithdrawalDays: null, refrigerated: false,
        notes: "Longa ação. Agitar bem antes de usar. Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "abamectan-ucb", brand: "Abamectan 1%", laboratory: "UCB (Uzinas Chimicas Brasileiras)",
        activeIngredient: "Abamectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "abamectina-1-elanco", brand: "Abamectina 1%", laboratory: "Elanco (antiga Bayer)",
        activeIngredient: "Abamectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em vacas em lactação. Nunca na veia ou no músculo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "abamect-fc-farmacampo", brand: "Abamect FC", laboratory: "Farmacampo",
        activeIngredient: "Abamectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas produtoras de leite para consumo. Tóxico para peixes.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "abamic-microsules", brand: "Abamic", laboratory: "Microsules",
        activeIngredient: "Abamectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não tratar animais com menos de 16 semanas. Não usar em vacas em lactação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ivonox-pour-on-noxon", brand: "Ivonox Pour On", laboratory: "Noxon",
        activeIngredient: "Ivermectina 0,5%", category: "ANTIPARASITARIO",
        presentation: "Solução pour-on", route: "Dorso", dose: "10 mL / 100 kg",
        slaughterWithdrawalDays: 48, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não aplicar em animal molhado. Não usar em vacas leiteiras em lactação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "genesis-iver-pour-on-eurofarma", brand: "Genesis Iver Pour-On", laboratory: "Eurofarma",
        activeIngredient: "Ivermectina 1%", category: "ANTIPARASITARIO",
        presentation: "Solução pour-on", route: "Dorso", dose: "1 mL / 20 kg",
        slaughterWithdrawalDays: 21, milkWithdrawalDays: null, refrigerated: false,
        notes: "Evitar contato com pele e olhos.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "fluron-gold-pour-on-vetbrands", brand: "Fluron Gold Pour On", laboratory: "Vetbrands (Sespo)",
        activeIngredient: "Cipermetrina + clorpirifós + fluazuron + butóxido de piperonila", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Solução pour-on", route: "Dorso", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 56, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "carrapaticida-sarnicida-ucb", brand: "Carrapaticida e Sarnicida UCB", laboratory: "UCB (Uzinas Chimicas Brasileiras)",
        activeIngredient: "Clorfenvinfós 50%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Concentrado para diluir", route: "Pulverização", dose: "1 mL por litro de água, a cada 25 a 30 dias",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Leite: 12 horas. Não usar em cães e gatos.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "farmitraz-vitalfarma", brand: "Farmitraz", laboratory: "Vitalfarma",
        activeIngredient: "Amitraz 12,5%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Concentrado para diluir", route: "Pulverização ou imersão", dose: "Pulverização: 20 mL para 10 L de água",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Leite: 24 horas. Evitar contato com pele e mucosas.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "fusion-cl-50-noxon", brand: "Fusion CL 50", laboratory: "Noxon",
        activeIngredient: "Fluazuron + clorpirifós + cipermetrina", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Solução pour-on", route: "Dorso", dose: "10 mL / 100 kg",
        slaughterWithdrawalDays: 24, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não misturar com óleos ou outros pesticidas. Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ibatox-ibasa", brand: "Ibatox Banheiro e Pulverização", laboratory: "Ibasa",
        activeIngredient: "Amitraz 12,5%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Concentrado para diluir", route: "Pulverização ou imersão", dose: "20 mL para 10 L de água",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Não deixar o animal lamber o pelo molhado.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "nokalt-ourofino", brand: "Nokalt", laboratory: "Ourofino",
        activeIngredient: "Amitraz 12,5%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Concentrado para diluir", route: "Pulverização", dose: "5 L de calda por bovino adulto",
        slaughterWithdrawalDays: 15, milkWithdrawalDays: 5, refrigerated: false,
        notes: "Leite: 120 horas. Tóxico para peixes.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "maximo-pulverizacao-biovet", brand: "Máximo Pulverização", laboratory: "Vaxxinova (antiga Biovet)",
        activeIngredient: "Cipermetrina + clorpirifós + butóxido de piperonila", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Concentrado para diluir", route: "Pulverização", dose: "4 L de calda por animal adulto (1:1000)",
        slaughterWithdrawalDays: 6, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Leite: 24 horas. Evitar contato com pele e inalação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "colosso-fc30-ourofino", brand: "Colosso FC30", laboratory: "Ourofino",
        activeIngredient: "Clorpirifós + cipermetrina + fention", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Concentrado para diluir", route: "Pulverização ou imersão", dose: "Conforme tabela da bula",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Usar equipamento de proteção e aplicar a favor do vento.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "topline-pour-on-boehringer", brand: "Topline Pour-On", laboratory: "Boehringer Ingelheim (antiga Merial)",
        activeIngredient: "Fipronil", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Solução pour-on", route: "Dorso", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 100, milkWithdrawalDays: null, refrigerated: false,
        notes: "Chuva forte pode reduzir a proteção.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "superhion-ourofino", brand: "Superhion", laboratory: "Ourofino",
        activeIngredient: "Fipronil 1% + fluazuron 3%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Solução pour-on", route: "Dorso", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 54, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não aplicar na chuva. Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "bovguard-msd", brand: "Bovguard", laboratory: "MSD Saúde Animal",
        activeIngredient: "Fipronil 1%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Solução pour-on", route: "Dorso", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 93, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "actyl-bimeda", brand: "Actyl Pour-On", laboratory: "Bimeda",
        activeIngredient: "Fipronil 1%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Solução pour-on", route: "Dorso", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 124, milkWithdrawalDays: null, refrigerated: false,
        notes: "Produto tóxico. Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "fiproline-duo-ceva", brand: "Fiproline Duo", laboratory: "Ceva",
        activeIngredient: "Fipronil 3%", category: "ANTIPARASITARIO", tags: ["CARRAPATICIDA"],
        presentation: "Solução pour-on / spot-on", route: "Dorso", dose: "Pour-on: 1 mL / 30 kg; spot-on: 1 mL / 15 kg",
        slaughterWithdrawalDays: 67, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "mata-bicheira-embrasvet", brand: "Mata Bicheira Embrasvet", laboratory: "Embrasvet",
        activeIngredient: "Clorfenvinfós + DDVP + cristal violeta", category: "OUTRO_SANITARIO", tags: ["MATA_BICHEIRA"],
        presentation: "Aerossol", route: "Sobre a ferida", dose: "Borrifar sobre a lesão",
        slaughterWithdrawalDays: 3, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Leite: 10 horas. Uso só externo; lavar as mãos após usar.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "mata-bicheira-biovet", brand: "Mata Bicheira Aerosol", laboratory: "Vaxxinova (antiga Biovet)",
        activeIngredient: "Clorfenvinfós + DDVP + violeta de genciana", category: "OUTRO_SANITARIO", tags: ["MATA_BICHEIRA"],
        presentation: "Aerossol", route: "Sobre a ferida", dose: "Borrifar a 10-20 cm da lesão",
        slaughterWithdrawalDays: 3, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Leite: 10 horas. Não inalar a névoa.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "imicarb-eurofarma", brand: "Imicarb", laboratory: "Eurofarma",
        activeIngredient: "Imidocarbe 12%", category: "ANTIPARASITARIO", tags: ["HEMOPARASITICIDA"],
        presentation: "Solução injetável", route: "Subcutânea", dose: "Babesiose: 1 mL / 100 kg; anaplasmose: 1 mL / 40 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em vacas produzindo leite.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "vivazene-ceva", brand: "Vivazene", laboratory: "Ceva",
        activeIngredient: "Diminazeno 7% + fenazona", category: "ANTIPARASITARIO", tags: ["HEMOPARASITICIDA"],
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "0,5 mL / 10 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: 5, refrigerated: false,
        notes: "Evitar superdose (risco de convulsão).",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "diminazine-b12-msd", brand: "Diminazine B12", laboratory: "MSD Saúde Animal (antiga Vallée)",
        activeIngredient: "Diminazeno 4% + vitamina B12", category: "ANTIPARASITARIO", tags: ["HEMOPARASITICIDA"],
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 30, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não diluir. Não usar em vacas em lactação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "beroseg-7-chemitec", brand: "Beroseg 7%", laboratory: "Chemitec",
        activeIngredient: "Diminazeno 7%", category: "ANTIPARASITARIO", tags: ["HEMOPARASITICIDA"],
        presentation: "Solução injetável", route: "Intramuscular", dose: "1 mL / 20 kg",
        slaughterWithdrawalDays: 30, milkWithdrawalDays: 21, refrigerated: false,
        notes: "Não passar de 10 mL por ponto de aplicação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "gasel-bravet", brand: "Gasel Solução", laboratory: "Bravet",
        activeIngredient: "Diminazeno 7%", category: "ANTIPARASITARIO", tags: ["HEMOPARASITICIDA"],
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "1 mL / 20 kg",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: false,
        notes: "Dividir doses grandes em vários pontos. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "virbazene-virbac", brand: "Virbazene", laboratory: "Virbac",
        activeIngredient: "Diminazeno 7%", category: "ANTIPARASITARIO", tags: ["HEMOPARASITICIDA"],
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "3,5 mg/kg, dose única",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: false,
        notes: "Carência não consta na bula: confirme com o veterinário.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "albendazole-bovinos-labovet", brand: "Albendazole Bovinos", laboratory: "Labovet",
        activeIngredient: "Albendazol 5%", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "1 mL / 10 kg (vermes); 2 mL / 10 kg (fascíola)",
        slaughterWithdrawalDays: 12, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Leite: 48 horas. Não passar da dose.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "calbendazole-calbos", brand: "Calbendazole 10%", laboratory: "Calbos",
        activeIngredient: "Albendazol 10%", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "1 mL / 20 kg",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em vacas em lactação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "farmazole-bovinos-10-vetoquinol", brand: "Farmazole Bovinos 10", laboratory: "Vetoquinol",
        activeIngredient: "Albendazol 10%", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "5 a 10 mg/kg conforme o parasita",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Leite: 2 dias.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "albendathor-10-tortuga", brand: "Albendathor 10", laboratory: "Tortuga (DSM)",
        activeIngredient: "Albendazol 10%", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "1 a 2 mL / 20 kg",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Leite: 48 horas. Evitar esforço antes e depois.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "endazol-10-cobalto-hipra", brand: "Endazol 10% Cobalto", laboratory: "Hipra",
        activeIngredient: "Albendazol 10% + cobalto", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "0,5 mL / 10 kg",
        slaughterWithdrawalDays: 12, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Leite: 48 horas. Agitar antes de usar.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ibazole-10-ibasa", brand: "Ibazole 10%", laboratory: "Ibasa",
        activeIngredient: "Albendazol 10%", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "1,5 mL / 20 kg (vermes); 1 mL / 10 kg (fascíola)",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Não passar da dose.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "albendazole-matsuda-vetecia", brand: "Albendazole Matsuda", laboratory: "Vetecia (Matsuda)",
        activeIngredient: "Albendazol 5%", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Leite: 72 horas. Agitar antes de usar.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "oxitetraciclina-20-la-biovet", brand: "Oxitetraciclina 20% LA", laboratory: "Vaxxinova (antiga Biovet)",
        activeIngredient: "Oxitetraciclina 20%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não diluir. Não usar em vacas em lactação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "oxitetraciclina-la-20-vitalfarma", brand: "Oxitetraciclina LA 20%", laboratory: "Vitalfarma",
        activeIngredient: "Oxitetraciclina 20%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Pode causar dor no local.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "oxitec-calbos", brand: "Oxitec", laboratory: "Calbos",
        activeIngredient: "Oxitetraciclina 10%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "3 a 6 mL para 100 a 200 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não associar com penicilinas.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "tetradur-boehringer", brand: "Tetradur", laboratory: "Boehringer Ingelheim (antiga Merial)",
        activeIngredient: "Oxitetraciclina 30%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Nunca diluir. Com 20 mg/kg a carência é 28 dias.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "berotetra-chemitec", brand: "Berotetra", laboratory: "Chemitec",
        activeIngredient: "Diminazeno + oxitetraciclina", category: "ANTIBIOTICO", tags: ["HEMOPARASITICIDA"],
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 30, milkWithdrawalDays: null, refrigerated: false,
        notes: "Evitar em animais jovens e fêmeas prenhes.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "florthal-minerthal", brand: "Florthal", laboratory: "Minerthal (Pharmalogic)",
        activeIngredient: "Florfenicol 30%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "1 mL / 15 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar junto com penicilinas ou cefalosporinas. Não usar em vacas em lactação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ceftiomax-biogenesis", brand: "Ceftiomax", laboratory: "Biogénesis Bagó",
        activeIngredient: "Ceftiofur 5%", category: "ANTIBIOTICO",
        presentation: "Suspensão injetável", route: "Intramuscular ou subcutânea", dose: "1 a 2 mg/kg",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Usar só na dose da bula para não deixar resíduo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "excede-zoetis", brand: "Excede", laboratory: "Zoetis",
        activeIngredient: "Ceftiofur (CCFA) 200 mg/mL", category: "ANTIBIOTICO",
        presentation: "Suspensão injetável", route: "Subcutânea (base da orelha)", dose: "1 mL / 30 kg",
        slaughterWithdrawalDays: 13, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Injeção em artéria pode matar o animal.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "excenel-zoetis", brand: "Excenel", laboratory: "Zoetis",
        activeIngredient: "Ceftiofur sódico", category: "ANTIBIOTICO",
        presentation: "Pó + diluente", route: "Intramuscular", dose: "1 mL / 50 kg por dia, 3 dias",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Não usar em animais alérgicos. Depois de preparado, siga a bula para guardar.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "cef-50-uniao-quimica", brand: "Cef-50", laboratory: "União Química",
        activeIngredient: "Ceftiofur 5%", category: "ANTIBIOTICO",
        presentation: "Suspensão injetável", route: "Intramuscular", dose: "1 mL / 50 kg por dia, até 3 dias",
        slaughterWithdrawalDays: 2, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Não usar em animais alérgicos a penicilinas.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "baytril-10-elanco", brand: "Baytril Injetável 10%", laboratory: "Elanco (antiga Bayer)",
        activeIngredient: "Enrofloxacino 10%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular, subcutânea ou na veia", dose: "0,5 mL / 20 kg por dia, 3 dias",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Não misturar com ferro, zinco, manganês ou cálcio.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "enro-flec-10-vansil", brand: "Enro Flec 10%", laboratory: "Vansil",
        activeIngredient: "Enrofloxacino 10%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "0,5 mL / 20 kg por dia",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Não usar em fêmeas prenhes ou em lactação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "chemitril-10-chemitec", brand: "Chemitril Injetável 10%", laboratory: "Chemitec",
        activeIngredient: "Enrofloxacino 10%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular, subcutânea ou na veia", dose: "1 mL / 40 kg por dia, 3 a 5 dias",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não misturar com vitaminas ou produtos com ferro, zinco ou cálcio.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "pentabiotico-zoetis", brand: "Pentabiótico Veterinário", laboratory: "Zoetis",
        activeIngredient: "Penicilinas + estreptomicina", category: "ANTIBIOTICO",
        presentation: "Pó + diluente", route: "Intramuscular", dose: "5 mL / 100 kg",
        slaughterWithdrawalDays: 22, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em animais alérgicos à penicilina. Depois de preparado, guardar na geladeira conforme a bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "pentabiotico-reforcado-zoetis", brand: "Pentabiótico Veterinário Reforçado", laboratory: "Zoetis",
        activeIngredient: "Penicilinas + estreptomicina", category: "ANTIBIOTICO",
        presentation: "Pó + diluente", route: "Intramuscular", dose: "5 mL / 100 kg",
        slaughterWithdrawalDays: 30, milkWithdrawalDays: 5, refrigerated: false,
        notes: "Leite: 4 a 5 dias. Depois de preparado, guardar na geladeira conforme a bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "estreptomax-ourofino", brand: "Estreptomax", laboratory: "Ourofino",
        activeIngredient: "Estreptomicina", category: "ANTIBIOTICO",
        presentation: "Pó + diluente", route: "Intramuscular", dose: "1,5 mL / 50 kg",
        slaughterWithdrawalDays: 5, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Leite: 24 horas. Evitar em fêmeas prenhes.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "agrovet-5000000-elanco", brand: "Agrovet 5.000.000", laboratory: "Elanco (antiga Novartis)",
        activeIngredient: "Penicilinas + estreptomicina", category: "ANTIBIOTICO",
        presentation: "Pó + diluente", route: "Intramuscular profunda", dose: "1 mL / 30 kg",
        slaughterWithdrawalDays: 30, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Pode causar reação alérgica. Depois de preparado, guardar conforme a bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "agrovet-ps-elanco", brand: "Agrovet PS", laboratory: "Elanco (antiga Novartis)",
        activeIngredient: "Benzilpenicilina procaína + di-hidroestreptomicina", category: "ANTIBIOTICO",
        presentation: "Suspensão injetável", route: "Intramuscular profunda", dose: "1 mL / 20 kg",
        slaughterWithdrawalDays: 30, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Leite: 3 dias. Conservação conforme a bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ketoprofeno-10-venco", brand: "Ketoprofeno 10% Injetável", laboratory: "Venco Saúde Animal",
        activeIngredient: "Cetoprofeno 10%", category: "ANTI_INFLAMATORIO",
        presentation: "Solução injetável", route: "Intramuscular, subcutânea ou na veia", dose: "3 mL / 100 kg por dia, 3 a 5 dias",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 1, refrigerated: false,
        notes: "Evitar em fêmeas prenhes.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    // ── Ampliação set/2026, parte 2: brucelose, botulismo, olho, hormônios e outros ──
    {
        key: "anavac-b19-ceva", brand: "Anavac B19", laboratory: "Ceva (antiga Hertape)",
        activeIngredient: "Brucella abortus amostra B19 (viva)", category: "VACINA", tags: ["BRUCELOSE_B19"],
        presentation: "Liofilizada + diluente", route: "Subcutânea", dose: "2 mL, dose única",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Só fêmeas de 3 a 8 meses. Nunca em machos. Aplicação por veterinário cadastrado. Evitar contato com olhos, boca e pele. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "anabortina-b19-boehringer", brand: "Anabortina B-19", laboratory: "Boehringer Ingelheim (antiga Merial)",
        activeIngredient: "Brucella abortus amostra B19 (viva)", category: "VACINA", tags: ["BRUCELOSE_B19"],
        presentation: "Liofilizada + diluente", route: "Subcutânea", dose: "2 mL, dose única",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Só fêmeas de 3 a 8 meses. Usar o mais rápido possível depois de preparada. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "vacina-brucelose-b19-labovet", brand: "Vacina Liofilizada contra Brucelose", laboratory: "Labovet",
        activeIngredient: "Brucella abortus amostra B19 (viva)", category: "VACINA", tags: ["BRUCELOSE_B19"],
        presentation: "Liofilizada + diluente", route: "Subcutânea", dose: "2 mL, dose única",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Só fêmeas de 3 a 8 meses. Nunca em machos. Evitar contato com olhos, boca e pele. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "vacina-botulismo-labovet", brand: "Vacina contra o Botulismo", laboratory: "Labovet",
        activeIngredient: "Botulismo tipos C e D", category: "VACINA", tags: ["BOTULISMO"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Primovacinação: 2 doses com 4 semanas de intervalo. Revacinação anual. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "botulinomax-ceva", brand: "Botulinomax", laboratory: "Ceva (antiga Hertape)",
        activeIngredient: "Botulismo + clostridioses", category: "VACINA", tags: ["BOTULISMO", "CLOSTRIDIOSE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "A partir de 4 meses; reforço 4 semanas depois; revacinação anual. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "starvac-labovet", brand: "Starvac", laboratory: "Labovet",
        activeIngredient: "Clostridioses + botulismo C e D", category: "VACINA", tags: ["CLOSTRIDIOSE", "BOTULISMO"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "1ª dose aos 4 meses, 2ª 4 semanas depois; revacinação anual. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "linovac-boehringer", brand: "Linovac", laboratory: "Boehringer Ingelheim (antiga Merial)",
        activeIngredient: "Botulismo tipos C e D", category: "VACINA", tags: ["BOTULISMO"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "5 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "2 doses com 4 a 7 semanas de intervalo; revacinação anual. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "kevac-hipra", brand: "Kevac", laboratory: "Hipra",
        activeIngredient: "Moraxella bovis (ceratoconjuntivite)", category: "VACINA", tags: ["CERATOCONJUNTIVITE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "3 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "2 doses com 21 a 30 dias de intervalo; revacinação anual, antes da seca. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "morak-5-hipra", brand: "Morak 5", laboratory: "Hipra",
        activeIngredient: "Moraxella bovis, bovoculi e ovis (ceratoconjuntivite)", category: "VACINA", tags: ["CERATOCONJUNTIVITE"],
        presentation: "Frasco multidose", route: "Subcutânea", dose: "3 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "2 doses com 21 dias de intervalo; reforço a cada 6 meses. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "tilosina-matsuda-20-vetecia", brand: "Tilosina Matsuda 20% Injetável", laboratory: "Vetecia (Matsuda)",
        activeIngredient: "Tilosina 20%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular ou na veia", dose: "1 mL / 20 kg por dia, 3 a 5 dias",
        slaughterWithdrawalDays: 21, milkWithdrawalDays: 5, refrigerated: false,
        notes: "Leite: 96 horas. Não misturar na seringa com outros produtos.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "zactran-boehringer", brand: "Zactran", laboratory: "Boehringer Ingelheim (antiga Merial)",
        activeIngredient: "Gamitromicina 15%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Subcutânea", dose: "1 mL / 25 kg, dose única",
        slaughterWithdrawalDays: 35, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas produtoras de leite para consumo.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "modificador-organico-bravet", brand: "Modificador Orgânico", laboratory: "Bravet",
        activeIngredient: "Aminoácidos, vitaminas e minerais", category: "VITAMINA_MINERAL",
        presentation: "Solução injetável", route: "Subcutânea", dose: "10 mL",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Carência zero para abate e leite.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "modificador-organico-ceva", brand: "Modificador Orgânico", laboratory: "Ceva (antiga Hertape)",
        activeIngredient: "Vitaminas, aminoácidos e minerais", category: "VITAMINA_MINERAL",
        presentation: "Solução injetável", route: "Subcutânea", dose: "10 a 20 mL",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: true,
        notes: "Carência zero para abate e leite.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "mov-msd", brand: "MOV Modificador Orgânico", laboratory: "MSD Saúde Animal (antiga Vallée)",
        activeIngredient: "Ferro, cobre, aminoácidos e vitaminas", category: "VITAMINA_MINERAL",
        presentation: "Solução injetável", route: "Subcutânea", dose: "10 mL",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Agitar antes de usar.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "clocio-bimeda", brand: "Clocio", laboratory: "Bimeda",
        activeIngredient: "Cloprostenol", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "2 mL",
        slaughterWithdrawalDays: 1, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Grávidas e asmáticos não devem manusear. Pode causar aborto em fêmea prenhe.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "cipionato-hc-ceva", brand: "Cipionato HC", laboratory: "Ceva (antiga Hertape)",
        activeIngredient: "Cipionato de estradiol 0,1%", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "1 mL",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmeas em lactação. Não usar em animais com tumor de mama ou útero.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "bioestrogen-biogenesis", brand: "Bioestrogen", laboratory: "Biogénesis Bagó",
        activeIngredient: "Benzoato de estradiol 0,1%", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Intramuscular profunda", dose: "Conforme o protocolo (0,5 a 10 mg)",
        slaughterWithdrawalDays: 10, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Leite: 30 horas. Grávidas não devem manusear.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "sincrosin-msd", brand: "Sincrosin", laboratory: "MSD Saúde Animal (antiga Vallée)",
        activeIngredient: "Cloprostenol", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "2 mL",
        slaughterWithdrawalDays: 1, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em fêmea prenhe (causa aborto).",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "prostaglandina-tortuga", brand: "Prostaglandina", laboratory: "Tortuga (DSM)",
        activeIngredient: "D-cloprostenol", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "2 mL",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: false,
        notes: "É absorvido pela pele e pode causar aborto: usar luvas. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "sincrocp-ourofino", brand: "SincroCP", laboratory: "Ourofino",
        activeIngredient: "Cipionato de estradiol 0,1%", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Intramuscular", dose: "1 mL",
        slaughterWithdrawalDays: 0, milkWithdrawalDays: 0, refrigerated: false,
        notes: "Não usar em fêmea prenhe.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "baytril-5-elanco", brand: "Baytril Injetável 5%", laboratory: "Elanco (antiga Bayer)",
        activeIngredient: "Enrofloxacino 5%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Subcutânea ou na veia", dose: "1 mL / 20 kg",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: null, refrigerated: false,
        notes: "Evitar em animais em fase de crescimento rápido.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "chemitril-2-5-chemitec", brand: "Chemitril Injetável 2,5%", laboratory: "Chemitec",
        activeIngredient: "Enrofloxacino 2,5%", category: "ANTIBIOTICO",
        presentation: "Solução injetável", route: "Intramuscular, subcutânea ou na veia", dose: "1 mL / 10 kg",
        slaughterWithdrawalDays: 28, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em animais produtores de leite.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "calbendazole-5-calbos", brand: "Calbendazole 5%", laboratory: "Calbos",
        activeIngredient: "Albendazol 5%", category: "VERMIFUGO",
        presentation: "Suspensão oral", route: "Oral", dose: "1,5 mL / 10 kg",
        slaughterWithdrawalDays: 14, milkWithdrawalDays: 3, refrigerated: false,
        notes: "Leite: 72 horas. Não dar a fêmeas nos primeiros 45 dias de prenhez.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "dexavet-bravet", brand: "Dexavet", laboratory: "Bravet",
        activeIngredient: "Dexametasona", category: "ANTI_INFLAMATORIO",
        presentation: "Solução injetável", route: "Intramuscular ou na veia", dose: "5 a 20 mg",
        slaughterWithdrawalDays: null, milkWithdrawalDays: 5, refrigerated: false,
        notes: "Não aplicar no último terço da prenhez. A bula não informa carência para abate: confirme com o veterinário.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "dexamax-msd", brand: "Dexamax", laboratory: "MSD Saúde Animal (antiga Vallée)",
        activeIngredient: "Dexametasona 0,2%", category: "ANTI_INFLAMATORIO",
        presentation: "Solução injetável", route: "Intramuscular, na veia ou na articulação", dose: "0,5 a 10 mL",
        slaughterWithdrawalDays: 21, milkWithdrawalDays: null, refrigerated: false,
        notes: "Pode provocar parto no último trimestre da prenhez.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ocitovet-vetbrands", brand: "Ocitovet", laboratory: "Vetbrands (Sespo)",
        activeIngredient: "Ocitocina", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Subcutânea, intramuscular ou na veia", dose: "7,5 a 10 mL (vaca)",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: false,
        notes: "Não usar em parto difícil sem corrigir antes a posição do bezerro. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "ocitocina-forte-ucb", brand: "Ocitocina Forte", laboratory: "UCB (Uzinas Chimicas Brasileiras)",
        activeIngredient: "Ocitocina", category: "HORMONIO_REPRODUCAO",
        presentation: "Solução injetável", route: "Subcutânea, intramuscular ou na veia", dose: "2 a 5 mL (subcutânea ou músculo)",
        slaughterWithdrawalDays: null, milkWithdrawalDays: null, refrigerated: true,
        notes: "Na veia, aplicar devagar. Carência não consta na bula.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "levamisol-matsuda-vetecia", brand: "Levamisol Injetável Matsuda", laboratory: "Vetecia (Matsuda)",
        activeIngredient: "Fosfato de levamisol 22,3%", category: "VERMIFUGO",
        presentation: "Solução injetável", route: "Subcutânea ou intramuscular", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 4, refrigerated: false,
        notes: "Leite: 96 horas. Não usar junto com organofosforados.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "levamisol-f-vetbrands", brand: "Levamisol F", laboratory: "Vetbrands (Sespo)",
        activeIngredient: "Fosfato de levamisol 22,3%", category: "VERMIFUGO",
        presentation: "Solução injetável", route: "Subcutânea ou intramuscular", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Leite: 48 horas.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "levamisol-noxon", brand: "Levamisol", laboratory: "Noxon",
        activeIngredient: "Levamisol 15%", category: "VERMIFUGO",
        presentation: "Solução injetável", route: "Subcutânea ou intramuscular", dose: "1 mL / 50 kg",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Não fazer o gado andar muito antes e depois da aplicação.",
        source: BULA, reviewedAt: '2026-09-16',
    },
    {
        key: "biopersol-forte-biogenesis", brand: "Biopersol Forte MV", laboratory: "Biogénesis Bagó",
        activeIngredient: "Levamisol 23,63%", category: "VERMIFUGO",
        presentation: "Solução injetável", route: "Subcutânea ou intramuscular", dose: "4,73 mg/kg",
        slaughterWithdrawalDays: 7, milkWithdrawalDays: 2, refrigerated: false,
        notes: "Leite: 48 horas. Evitar esforço antes e depois.",
        source: BULA, reviewedAt: '2026-09-16',
    },
];

const CATALOG_BY_KEY = new Map(PHARMACY_CATALOG.map((item) => [item.key, item]));

export function findCatalogItem(key) {
    if (!key) return null;
    return CATALOG_BY_KEY.get(String(key)) || null;
}
